### ISSUE TITLE
abraces \Repeat already defined for Springer template

### ISSUE THREAD

**Issue by hiiroo** [wgrundlingh/abraces#1]
Hello there, 

I got the following error when I attempted to use abraces in Springer sn-mathphy document class. If there is a workaround I could't find it. Thanks in advance.

```
/usr/local/texlive/2019/texmf-dist/tex/latex/abraces/abraces.sty:39: LaTeX Error: Command \Repeat already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...  
```

**Comment by wgrundlingh** [comment]
Thanks for picking this up. I'll update the code to use a more personalized (or package-specific) macro name to avoid future issues. I'll let you know when I'm able to post a fix and you can update the package.

**Comment by wgrundlingh** [comment]
An update has been pushed to CTAN, replacing `\Repeat` with `\Repeat@br@ces`. This should avoid future package conflicts.
