### ISSUE TITLE
abraces has to be loaded after xcolor

### ISSUE THREAD

**Issue by mbertucci47** [wgrundlingh/abraces#2]
Since abraces now does `\let\bracecolor\color`, if `\color` is not defined at the time abraces is loaded, then `\bracecolor` is not either. Here's an example.
```tex
\documentclass{article}

\usepackage{abraces}
\usepackage{xcolor}

\newcommand{\FnD}{%
  \textrm{The quick brown fox jumped over the lazy dog}}

\begin{document}

% this works
$\aunderbrace[l2D1r000@{\color{blue!70!black}}l1D2r]{\FnD}$

% this errors
$\aunderbrace[l2D1r000@{\bracecolor{blue!70!black}}l1D2r]{\FnD}$

\end{document}
```
If you switch the loading order of xcolor and abraces then everything works. Either a note should be added in the documentation or `\bracecolor` should be defined with `\def` or `\renewcommand`.

**Comment by wgrundlingh** [comment]
An update has been pushed to CTAN, adding [`xcolor`](//ctan.org/pkg/xcolor) as a dependency. This will always make `\color` available, and consequently also `\bracecolor`.
